version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: todo_redis
    volumes:
      - redis_data:/data
    networks:
      - todo_network

  postgres:
    image: postgres:15-alpine
    container_name: todo-postgres
    environment:
      POSTGRES_DB: test_blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe1144EodT5
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo_network

  app:
    build: .
    container_name: todo-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=test_blog
      - DB_USER=postgres
      - DB_PASSWORD=qwe1144EodT5
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - todo_network

volumes:
  postgres_data:
  redis_data:

networks:
  todo_network:
    driver: bridge